# Python version
FROM python:3.11-slim

# Update packages and install necessary dependencies for CRIU
RUN apt-get update && apt-get install -y --no-install-recommends \
    criu \
    iproute2 \
    iputils-ping \
    procps \
    sudo \
    libnftables1 \
    nftables \
    iptables \
    curl ca-certificates \
    libglib2.0-0 \
 && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir torch torchvision --index-url https://download.pytorch.org/whl/cpu
RUN pip install --no-cache-dir ultralytics
RUN pip uninstall -y opencv-python opencv-python-headless \
 && pip install --no-cache-dir opencv-python-headless
RUN python3 -c "import cv2; print('cv2 OK', cv2.__version__)"

# Install python packages for wrapper
RUN pip install --no-cache-dir pymavlink sysv_ipc

COPY src /app/src
COPY mission/ /app/missions/

WORKDIR /app/src

# Configure passwordless sudo for all users, needed to call CRIU
# RUN echo "ALL ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/nopasswd && \
#     chmod 0440 /etc/sudoers.d/nopasswd

# Command to run script
CMD ["sleep", "infinity"]
# CMD ["python3", "-u", "supervisor.py"]


