--connection udp:127.0.0.1:14551 
--mission /app/missions/complex_survey/mission.waypoints 
--airspeed-m-s 5
--capture-dir  /mnt/checkpoints/capture
--camera-ack-timeout-s 20
--model-path /app/missions/complex_survey/yolov8s.pt