services:
  patrol_mission:
    image: antzikas/mission-container:latest
    container_name: patrol_mission
    privileged: true
    network_mode: host
    env_file:
      - ../../mission/mission.env
    volumes:
      - ../../experiment_logs:/mnt/checkpoints
    stdin_open: true
    tty: true
    restart: "on-failure"